export const academyModules = [
  {
    academy: "Business Coaching Academy",
    title: "Welcome to Purity OS",
    lessons: ["Welcome to Purity OS", "How to Use the Platform"],
    pdfs: ["Welcome Guide", "Platform Roadmap", "Success Checklist"],
    quiz: ["How do you navigate the platform?", "Where are resources found?", "What is the goal of the academy?"],
    progress: 100,
  },
  {
    academy: "Business Coaching Academy",
    title: "Benchmarks",
    lessons: ["Benchmarks", "KPIs for Growth", "Building Accountability"],
    pdfs: ["Weekly KPI Tracker", "Business Scorecard", "Monthly Review Worksheet"],
    quiz: ["What booking rate should we aim for?", "Why does client retention matter?", "What should be reviewed weekly?"],
    progress: 62,
  },
  {
    academy: "Business Coaching Academy",
    title: "Leveling Up",
    lessons: ["Working ON Your Business", "CEO Mindset", "Delegation"],
    pdfs: ["CEO Weekly Planner", "Time Blocking Worksheet", "Delegation Checklist"],
    quiz: ["What does working ON the business mean?", "Why is admin time important?", "What should be delegated first?"],
    progress: 45,
  },
  {
    academy: "Business Coaching Academy",
    title: "Client Experience",
    lessons: ["Guest Experience", "Building Loyalty", "Creating Referrals"],
    pdfs: ["Client Journey Checklist", "Referral Strategy", "Follow-Up Templates"],
    quiz: ["What creates a great guest experience?", "Why do follow-ups matter?", "How do referrals grow the business?"],
    progress: 30,
  },
  {
    academy: "Business Coaching Academy",
    title: "Social Media",
    lessons: ["Why Social?", "Social Strategies", "Social Media Commitment"],
    pdfs: ["30-Day Content Calendar", "Caption Library", "Daily Posting Checklist"],
    quiz: ["Why is social media important?", "What does consistency build?", "Why should assistants understand brand standards?"],
    progress: 20,
  },
  {
    academy: "Business Coaching Academy",
    title: "Accountant & Payroll",
    lessons: ["Hire an Accountant", "Payroll Basics", "Financial Systems"],
    pdfs: ["Hiring Checklist", "Payroll Guide", "Tax Preparation Worksheet"],
    quiz: ["Why hire an accountant?", "What should payroll track?", "Why are financial systems important?"],
    progress: 10,
  },
  {
    academy: "Business Coaching Academy",
    title: "The Three B's",
    lessons: ["Body", "Boundaries", "Balance"],
    pdfs: ["Daily Routine Planner", "Boundary Worksheet", "Weekly Balance Tracker"],
    quiz: ["Why does leadership energy matter?", "Why are boundaries important?", "How does balance prevent burnout?"],
    progress: 5,
  },
  {
    academy: "Business Coaching Academy",
    title: "Ultimate Assistant Guide",
    lessons: ["The UAG", "Implementation", "Training Your Team"],
    pdfs: ["Assistant Handbook", "SOP Templates", "Onboarding Guide"],
    quiz: ["What is the assistant roadmap?", "Why do SOPs matter?", "How should expectations be documented?"],
    progress: 0,
  },
  {
    academy: "Assistant University",
    title: "Welcome to The AU",
    lessons: ["Welcome to The Assistant University", "Orientation", "How AU Works"],
    pdfs: ["AU Welcome Guide", "Assistant University Roadmap", "Student Checklist"],
    quiz: ["What is AU designed to help build?", "What should students complete first?", "Where are downloads located?"],
    progress: 100,
  },
  {
    academy: "Assistant University",
    title: "Week 1 - The Foundation",
    lessons: ["Snapshot", "Ultimate Assistant Guide", "Charging Your Worth", "Compensation", "Payroll", "Assistant Pay Calculator", "Assistant Hourly Rate", "Assistant Goal Setting", "Assistant Earning Potential"],
    pdfs: ["Assistant Workbook", "Payroll Calculator", "Pay Worksheet", "Goal Sheet", "Earning Potential Calculator"],
    quiz: ["Why is the assistant guide important?", "Why should pricing be reviewed?", "What should payroll track?", "Why does goal setting matter?"],
    progress: 75,
  },
  {
    academy: "Assistant University",
    title: "Week 2 - Education",
    lessons: ["Snapshot", "Education", "Phases", "Basic / Quick Test Outs", "39 Week Curriculum", "Recruiting", "Interviewing", "Onboarding", "Assistant First Day", "Orientation"],
    pdfs: ["Luxury Language Cheat Sheet", "Interview Sheet", "Onboarding Checklist", "Training Checklist", "39 Week Curriculum Template"],
    quiz: ["Why does education matter?", "What are test outs used for?", "Why should onboarding be structured?", "What makes a strong first day?"],
    progress: 45,
  },
  {
    academy: "Assistant University",
    title: "Week 3 - Coaching + Mentoring",
    lessons: ["Snapshot", "Leading with a Servant Heart", "Debriefing", "The Tough Stuff", "One-on-Ones", "Coaching vs Mentoring", "Slow Growing Assistants", "Work Attire"],
    pdfs: ["Conversation Scripts", "Leadership Workbook", "One-on-One Template", "Debrief Checklist"],
    quiz: ["What does servant leadership mean?", "Why are debriefs important?", "How should tough conversations be handled?", "Why are 1:1s important?"],
    progress: 25,
  },
  {
    academy: "Assistant University",
    title: "Week 4 - Scaling",
    lessons: ["Snapshot", "Your Next Assistant", "Admin Days", "Dream Income", "Strategic Scheduling", "Workflow - Maintenance", "Workflow - Color", "Parts + Labor", "Trackers", "Station Sharing"],
    pdfs: ["Tracker Sheets", "Scheduling Planner", "Growth Workbook", "Workflow Templates", "Dream Income Worksheet"],
    quiz: ["When should you think about the next assistant?", "Why are admin days important?", "What does strategic scheduling help with?", "Why track parts and labor?"],
    progress: 10,
  },
  {
    academy: "Assistant University",
    title: "Celebrate",
    lessons: ["You Did It", "Graduation", "Next Steps"],
    pdfs: ["Certificate Placeholder", "Review Request", "Next Steps Plan"],
    quiz: ["What is the next step after completing AU?", "Why celebrate progress?", "How do you continue implementation?"],
    progress: 0,
  },
];

export const comingSoon = [
  "AI Image Generator",
  "On-Site Business Visits",
  "Live Coaching Calendar",
  "Community Chat",
  "Business KPI Dashboard",
  "ALMA Business Assistant",
  "Template Library",
  "Certification Program",
  "Build Your Booking Platform",
  "Website Color Customizer",
];

export const businessTools = [
  "Assistant Pay Calculator",
  "Hourly Rate Calculator",
  "Profit Calculator",
  "Revenue Calculator",
  "Booking Calculator",
  "Payroll Calculator",
  "Chair Utilization Calculator",
  "Growth Calculator",
  "Income Goal Calculator",
];
